---
global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:


rule_files:


scrape_configs:
  - job_name: app
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['localhost:3030']
