env: local
email:
  password: bwch rbes cemw ayyc
  name: Device - Online Device Shop
  email: asroka4ev@gmail.com

kafka:
  topics:
    auth: NEW_USER_EMAILS
    order: NEW_ORDERS_EMAIL
  brokerAddr: 127.0.0.1:9092