// Code generated by MockGen. DO NOT EDIT.
// Source: internal/broker/worker/worker.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWorker is a mock of Worker interface.
type MockWorker struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerMockRecorder
}

// MockWorkerMockRecorder is the mock recorder for MockWorker.
type MockWorkerMockRecorder struct {
	mock *MockWorker
}

// NewMockWorker creates a new mock instance.
func NewMockWorker(ctrl *gomock.Controller) *MockWorker {
	mock := &MockWorker{ctrl: ctrl}
	mock.recorder = &MockWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorker) EXPECT() *MockWorkerMockRecorder {
	return m.recorder
}

// MustStart mocks base method.
func (m *MockWorker) MustStart() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MustStart")
}

// MustStart indicates an expected call of MustStart.
func (mr *MockWorkerMockRecorder) MustStart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MustStart", reflect.TypeOf((*MockWorker)(nil).MustStart))
}

// Produce mocks base method.
func (m *MockWorker) Produce() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Produce")
}

// Produce indicates an expected call of Produce.
func (mr *MockWorkerMockRecorder) Produce() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockWorker)(nil).Produce))
}
