env: local

server:
  port: 3001
  timeout: 10s

broker:
  addr: 127.0.0.1:9092
  topics:
    metrics:
      usersAmount: USERS_METRIC
      orders: ORDER_METRIC
      latency: LATENCY_METRIC
cache:
  addr: 127.0.0.1:4001

services:
  userAddr: 127.0.0.1:3002
  deviceAddr: 127.0.0.1:3003
  orderAddr: 127.0.0.1:3005
  collAddr: 127.0.0.1:3004