env: local
db:
  host: 127.0.0.1
  port: 4005
  user: postgres
  password: 1787
  name: template1
  sslmode: disable
grpc:
  port: 3005
  timeout: 5s
broker:
  brokerAddr: 127.0.0.1:9092
  userTopicIn: USER_SERVICE_IN_TX
  userTopicOut: USER_SERVICE_OUT_TX
  deviceTopicIn: DEVICE_SERVICE_IN_TX
  deviceTopicOut: DEVICE_SERVICE_OUT_TX
  collectionTopicIn: COLLECTION_SERVICE_IN_TX
  collectionTopicOut: COLLECTION_SERVICE_OUT_TX
services:
  deviceAddr: 127.0.0.1:3003