env: local
db:
  host: 127.0.0.1
  port: 4005
  user: postgres
  password: 1787
  name: template1
  sslmode: disable
grpc:
  port: 3005
  timeout: 5s
kafka:
  brokerAddr: 127.0.0.1:9092
  userOutTopic: USER_SERVICE_OUT_TX
  userInTopic: USER_SERVICE_IN_TX
  deviceTopic: DEVICE_SERVICE_TX
  collectionTopic: COLLECTION_SERVICE_TX
services:
  deviceAddr: 127.0.0.1:3003