env: local
grpc:
  port: 3002
  timeout: 5s
db:
  host: 127.0.0.1
  port: 4002
  user: postgres
  password: 1787
  name: template1
  sslmode: disable

kafka:
  brokerAddr: 127.0.0.1:9092
  emailTopic: NEW_USER_EMAILS
  workerTopicIn: USER_SERVICE_IN_TX
  workerTopicOut: USER_SERVICE_OUT_TX

services:
  device:
    addr: 127.0.0.1:3003